
     /*
	Name: pays.sql
	Date: Jully 09, 2004
	Author: Philippe Torloting www.phive-online.com
	Apropos: 1 table Mysql contenant 238 pays du monde en fr	
    */
	

  CREATE TABLE  tpays 
  (
		PAYSID INT NOT NULL auto_increment,
		PAYSNAME VARCHAR(80) NOT NULL,
		PAYSCODE CHAR(2) NOT NULL,
		PRIMARY KEY  (PAYSID)
  );
  

INSERT INTO tpays (PAYSNAME,PAYSCODE) values('France','fr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Afghanistan','af');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Afrique du sud','za');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Albanie','al');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Alg�rie','dz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Allemagne','de');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Arabie saoudite','sa');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Argentine','ar');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Australie','au');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Autriche','at');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Belgique','be');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Br�sil','br');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bulgarie','bg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Canada','ca');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Chili','cl');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Chine (R�p. pop.)','cn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Colombie','co');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cor�e, Sud','kr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Costa Rica','cr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Croatie','hr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Danemark','dk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�gypte','eg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�mirats arabes unis','ae');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�quateur','ec');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�tats-Unis','us');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('El Salvador','sv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Espagne','es');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Finlande','fi');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Gr�ce','gr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Hong Kong','hk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Hongrie','hu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Inde','in');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Indon�sie','id');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Irlande','ie');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Isra�l','il');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Italie','it');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Japon','jp');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Jordanie','jo');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Liban','lb');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Malaisie','my');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Maroc','ma');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mexique','mx');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Norv�ge','no');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nouvelle-Z�lande','nz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('P�rou','pe');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Pakistan','pk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Pays-Bas','nl');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Philippines','ph');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Pologne','pl');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Porto Rico','pr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Portugal','pt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('R�publique tch�que','cz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Roumanie','ro');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Royaume-Uni','uk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Russie','ru');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Singapour','sg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Su�de','se');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Suisse','ch');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Taiwan','tw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Thailande','th');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Turquie','tr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ukraine','ua');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Venezuela','ve');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Yougoslavie','yu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Samoa','as');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Andorre','ad');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Angola','ao');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Anguilla','ai');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Antarctique','aq');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Antigua et Barbuda','ag');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Arm�nie','am');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Aruba','aw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Azerba�djan','az');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bahamas','bs');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bahrain','bh');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bangladesh','bd');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bi�lorussie','by');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Belize','bz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Benin','bj');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bermudes (Les)','bm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bhoutan','bt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bolivie','bo');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bosnie-Herz�govine','ba');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Botswana','bw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Bouvet (�les)','bv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Territoire britannique de l\'oc�an Indien','io');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Vierges britanniques (�les)','vg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Brunei','bn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Burkina Faso','bf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Burundi','bi');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cambodge','kh');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cameroun','cm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cap Vert','cv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cayman (�les)','ky');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('R�publique centrafricaine','cf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Tchad','td');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Christmas (�le)','cx');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cocos (�les)','cc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Comores','km');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('R�p. D�m. du Congo','cg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cook (�les)','ck');
INSERT INTO tpays (PAYSNAME,PAYSCODE)  values('Cuba','cu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Chypre','cy');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Djibouti','dj');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Dominique','dm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('R�publique Dominicaine','do');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Timor','tp');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guin�e Equatoriale','gq');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�rythr�e','er');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Estonie','ee');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ethiopie','et');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Falkland (�le)','fk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('F�ro� (�les)','fo');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Fidji (R�publique des)','fj');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guyane fran�aise','gf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Polyn�sie fran�aise','pf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Territoires fran�ais du sud','tf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Gabon','ga');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Gambie','gm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('G�orgie','ge');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ghana','gh');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Gibraltar','gi');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Groenland','gl');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Grenade','gd');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guadeloupe','gp');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guam','gu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guatemala','gt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guin�e','gn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guin�e-Bissau','gw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Guyane','gy');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ha�ti','ht');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Heard et McDonald (�les)','hm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Honduras','hn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Islande','is');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Iran','ir');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Irak','iq');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('C�te d\'Ivoire','ci');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Jama�que','jm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Kazakhstan','kz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Kenya','ke');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Kiribati','ki');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Cor�e du Nord','kp');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Koweit','kw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Kirghizistan','kg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Laos','la');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Lettonie','lv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Lesotho','ls');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Lib�ria','lr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Libye','ly');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Liechtenstein','li');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Lithuanie','lt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Luxembourg','lu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Macau','mo');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mac�doine','mk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Madagascar','mg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Malawi','mw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Maldives (�les)','mv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mali','ml');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Malte','mt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Marshall (�les)','mh');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Martinique','mq');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mauritanie','mr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Maurice','mu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mayotte','yt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Micron�sie (�tats f�d�r�s de)','fm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Moldavie','md');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Monaco','mc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mongolie','mn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Montserrat','ms');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mozambique','mz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Myanmar','mm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Namibie','na');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nauru','nr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nepal','np');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Antilles n�erlandaises','an');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nouvelle Cal�donie','nc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nicaragua','ni');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Niger','ne');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Nigeria','ng');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Niue','nu');
INSERT INTO tpays (PAYSNAME,PAYSCODE)  values('Norfolk (�les)','nf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Mariannes du Nord (�les)','mp');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Oman','om');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Palau','pw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Panama','pa');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Papouasie-Nouvelle-Guin�e','pg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Paraguay','py');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Pitcairn (�les)','pn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Qatar','qa');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('R�union (La)','re');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Rwanda','rw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('G�orgie du Sud et Sandwich du Sud (�les)','gs');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Saint-Kitts et Nevis','kn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Sainte Lucie','lc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Saint Vincent et les Grenadines','vc');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Samoa','ws');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Saint-Marin (R�p. de)','sm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('S�o Tom� et Pr�ncipe (R�p.)','st');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('S�n�gal','sn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Seychelles','sc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Sierra Leone','sl');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Slovaquie','sk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Slov�nie','si');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Somalie','so');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Sri Lanka','lk');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Sainte H�l�ne','sh');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Saint Pierre et Miquelon','pm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Soudan','sd');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Suriname','sr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Svalbard et Jan Mayen (�les)','sj');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Swaziland','sz');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Syrie','sy');
INSERT INTO tpays(PAYSNAME,PAYSCODE)  values('Tadjikistan','tj');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Tanzanie','tz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Togo','tg');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Tokelau','tk');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Tonga','to');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Trinit� et Tobago','tt');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Tunisie','tn');
INSERT INTO tpays(PAYSNAME,PAYSCODE) values('Turkm�nistan','tm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Turks et Ca�ques (�les)','tc');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Tuvalu','tv');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('�les Mineures �loign�es des �tats-Unis','um');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ouganda','ug');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Uruguay','uy');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Ouzb�kistan','uz');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Vanuatu','vu');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Vatican (Etat du)','va');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Vietnam','vn');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Vierges (�les)','vi');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Wallis et Futuna (�les)','wf');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Sahara Occidental','eh');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Yemen','ye');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Za�re','zr');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Zambie','zm');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('Zimbabwe','zw');
INSERT INTO tpays (PAYSNAME,PAYSCODE) values('La Barbad','bb');
